//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Operation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Master
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Catagory_Id { get; set; }
        public string Catagory { get; set; }
    
        public virtual Tbl_Catagory Tbl_Catagory { get; set; }
    }
}
